/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.henriquemcc.chat.java;

public class ClientMain {
    public String getGreeting() {
        return "Hello World From Client!";
    }

    public static void main(String[] args) {
        System.out.println(new ClientMain().getGreeting());
    }
}
