/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.henriquemcc.chat.java;

public class ServerMain {
    public String getGreeting() {
        return "Hello World From Server!";
    }

    public static void main(String[] args) {
        System.out.println(new ServerMain().getGreeting());
    }
}
