/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.henriquemcc.chat.java;

import org.junit.Test;
import static org.junit.Assert.*;

public class ServerMainTest {
    @Test public void appHasAGreeting() {
        ServerMain classUnderTest = new ServerMain();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
