package servidor.controlador;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import comum.modelo.ProtocoloTransporte;
import servidor.visao.MenuConsoleServidor;

import java.io.IOException;
import java.net.ServerSocket;

public class Servidor {

    /**
     * Porta do servidor.
     */
    public static Integer portaServidor = null;

    /**
     * Protocolo da camada de transporte utilizado na comunicação com os clientes.
     */
    public static ProtocoloTransporte protocoloTransporte = null;

    public static boolean programaEmExecucao = true;

    public static ControladorMensagens controladorMensagens =  new ControladorMensagens();

    public static Thread threadComunicacaoClientes = new Thread() {

        private void comunicacaoClienteTcp() {
            try{
                ServerSocket serverSocket = new ServerSocket(portaServidor);
                while (true) {
                    TratadorClienteTcp tratadorClienteTcp = new TratadorClienteTcp(serverSocket.accept());
                    tratadorClienteTcp.start();
                }
            } catch (IOException e) {
                e.printStackTrace();
            }
        }

        private void comunicacaoClienteUdp() {

        }

        @Override
        public void run() {
            if (protocoloTransporte == ProtocoloTransporte.TCP)
                comunicacaoClienteTcp();
            else if (protocoloTransporte == ProtocoloTransporte.UDP)
                comunicacaoClienteUdp();
        }
    };

    public static void configuracaoInicial() {
        while (portaServidor == null)
            MenuConsoleServidor.menuPortaServidor();
        while (protocoloTransporte == null)
            MenuConsoleServidor.menuProtocoloTransporte();
    }

    public static void main(String[] args) {

        // Temporário
        System.out.println("servidor.controlador.Servidor rodando");
        portaServidor = 65535;
        protocoloTransporte = ProtocoloTransporte.TCP;

        configuracaoInicial();
        threadComunicacaoClientes.start();
    }
}
